In [1]:
import numpy as np
import pandas as pd
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report,confusion_matrix
from sklearn.tree import DecisionTreeClassifier


In [2]:
# Question1

# load dataset
iris=datasets.load_iris()
x=iris.data
y=iris.target

In [3]:
x_train, x_test, y_train, y_test=train_test_split(x,y,test_size=0.2, random_state=42)

In [4]:
model=LogisticRegression(multi_class='ovr',solver='liblinear')

In [5]:
model.fit(x_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(


LogisticRegression(multi_class='ovr', solver='liblinear')

In [6]:
y_pred=model.predict(x_test)

In [7]:

y_pred

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0])

In [8]:
y_test

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0])

In [9]:
accuracy=accuracy_score(y_test,y_pred)
accuracy

1.0

In [10]:

# Question2


In [11]:
from sklearn.tree import DecisionTreeClassifier
import matplotlib as plt

In [14]:
# dataset downloaded from lms
df=pd.read_csv('weather.csv')

In [15]:
x_train, x_test, y_train, y_test=train_test_split(x,y,test_size=0.3,random_state=7)

In [16]:
# # with gini index

# model_gini=DecisionTreeClassifier(criterion='gini')
# model_gini.fit(x_train,y_train)

# y_pred_gini=model_gini.predict(x_test)
# y_pred

# print("Confusion Matrix: ", confusion_matrix(y_test,y_pred_gini))
# print("Accuracy", accuracy_score(y_test,y_pred_gini))
# print("Report: ", classification_report(y_test,y_pred_gini))

In [17]:
# with entropy

model_entropy=DecisionTreeClassifier(criterion='entropy', max_depth=3)
model_entropy.fit(x_train,y_train)

y_pred_entropy=model_entropy.predict(x_test)
y_pred_entropy


print("Confusion Matrix: ", confusion_matrix(y_test,y_pred_entropy))
print("Accuracy: ", accuracy_score(y_test,y_pred_entropy)*100)
print("Report: ", classification_report(y_test,y_pred_entropy))

# plt.figure(figsize=(15, 10))
# feature_names= ['outlook','temp','humidity','windy']
# class_names=['P','NP']
# plot_tree(y_pred_entropy, filled=True, feature_names=feature_names, class_names=class_names, rounded=True)
# plt.show()


Confusion Matrix:  [[12  0  0]
 [ 0 14  2]
 [ 0  3 14]]
Accuracy:  88.88888888888889
Report:                precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       0.82      0.88      0.85        16
           2       0.88      0.82      0.85        17

    accuracy                           0.89        45
   macro avg       0.90      0.90      0.90        45
weighted avg       0.89      0.89      0.89        45



In [18]:
# Question 3

data = pd.read_csv('BankNote_Authentication.csv')
X = data.drop(columns='class')
y = data['class']



In [19]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)


In [20]:
cart_model = DecisionTreeClassifier(random_state=42)
cart_model.fit(X_train, y_train)
y_pred = cart_model.predict(X_test)

In [21]:

accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)

print(f"Accuracy: {accuracy}")
print("Classification Report:")
print(report)

Accuracy: 0.9805825242718447
Classification Report:
              precision    recall  f1-score   support

           0       0.97      0.99      0.98       229
           1       0.99      0.97      0.98       183

    accuracy                           0.98       412
   macro avg       0.98      0.98      0.98       412
weighted avg       0.98      0.98      0.98       412

