In [1]:
import numpy as np

In [ ]:

arr=np.array([1,2,3,6,4,5])
print(arr)
arr=np.flip(arr)
print(arr)

[1 2 3 6 4 5]
[5 4 6 3 2 1]


In [ ]:
arr=np.array([[1,2,3],[2,4,5],[1,2,3]])
arf=arr.flatten()
print(arf)

[1 2 3 2 4 5 1 2 3]


In [ ]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[1,2],[3,4]])
comparr=arr1==arr2
eqarr=comparr.all()
print(eqarr)

True


In [ ]:
x=np.array([1,2,3,4,5,1,2,1,1,1,])
print(x)

print("Most Frequent value in the given array x:")
maxele=np.bincount(x).argmax()
print(maxele)
print(np.where(x==maxele)[0])



Most Frequent value in the given array x:
1
[0 5 7 8 9]


In [ ]:
x=([1,1,1,2,3,4,2,4,3,3])
print(x)
print("Most frequent value in above array y")
y = np.bincount(x)
#print(y)
maxele = max(y)
#print(maxele)

for i in range(len(y)):
    if y[i] == maxele:
        print(i, np.where(x==y[i])[0])



Most frequent value in above array y
1 [4 8 9]
3 [4 8 9]


In [ ]:
gfg=np.matrix('[4,1,9;12,3,1;4,5,6]')
print(gfg)
print(np.sum(gfg))
print("Sum of each row", np.sum(gfg, axis=1))
print("Sum of each column", np.sum(gfg, axis=0))

[[ 4  1  9]
 [12  3  1]
 [ 4  5  6]]
45
Sum of each row [[14]
 [16]
 [15]]
Sum of each column [[20  9 16]]


In [ ]:
n_array=np.mat([[55,25,15],[30,44,2],[11,45,77]])
print(n_array)
evalue, evect =np.linalg.eig(n_array)
print("Eigen value of matrix: ", evalue)
print("Eigen vectors of matrix: ", evect)


[[55 25 15]
 [30 44  2]
 [11 45 77]]
Eigen value of matrix:  [98.16835147 28.097044   49.73460452]
Eigen vectors of matrix:  [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]


In [ ]:
print("Inverse of matrix:", np.linalg.inv(n_array))
print("Determinant of matirx: ", np.linalg.det(n_array))

[[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
137180.0000000001


In [ ]:
diag=np.diagonal(n_array)

print("diagonal elements of are:", diag)
print("Sum of diagonal elements: ", sum(diag))

diagonal elements of are: [55 44 77]
Sum of diagonal elements:  176


In [ ]:
p=np.matrix([[1, 2], [2, 3]] )
q=np.matrix([[4, 5], [6, 7]] )

res=np.dot(p,q)

# res=p@q

print("Dot product = ", res)
print("Covariance: ", np.cov(p,q))

Dot product =  [[16 19]
 [26 31]]
Covariance:  [[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]


In [ ]:
p=np.matrix([[1, 2], [2, 3], [4, 5]]  )
q=np.matrix([[4, 5, 1], [6, 7, 2]]  )

res=np.dot(p,q)

# res=p@q

print("Dot product = ", res)
# print("Covariance: ", np.cov(p,q)) covariance not possible as order is not same of p and q

Dot product =  [[16 19  5]
 [26 31  8]
 [46 55 14]]


In [ ]:
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])

print("\nInner product of matrices x and y =")
print(np.inner(x, y))
print("\nOuter product of matrices x and y =")
print(np.outer(x, y))

x_flat = x.flatten()
y_flat = y.flatten()

result = np.transpose([np.tile(x_flat, len(y_flat)), np.repeat(y_flat, len(x_flat))])
print(result)



Inner product of matrices x and y =
[[17 52]
 [13 62]]

Outer product of matrices x and y =
[[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
[[ 2  1]
 [ 3  1]
 [ 4  1]
 [ 3  1]
 [ 2  1]
 [ 9  1]
 [ 2  5]
 [ 3  5]
 [ 4  5]
 [ 3  5]
 [ 2  5]
 [ 9  5]
 [ 2  0]
 [ 3  0]
 [ 4  0]
 [ 3  0]
 [ 2  0]
 [ 9  0]
 [ 2  5]
 [ 3  5]
 [ 4  5]
 [ 3  5]
 [ 2  5]
 [ 9  5]
 [ 2 10]
 [ 3 10]
 [ 4 10]
 [ 3 10]
 [ 2 10]
 [ 9 10]
 [ 2  3]
 [ 3  3]
 [ 4  3]
 [ 3  3]
 [ 2  3]
 [ 9  3]]


In [ ]:
array = np.array([[1, -2, 3],[-4, 5, -6]])
print("Absolute values:", np.absolute(array))

farr=array.flatten()

print("\nFlattened Array:")
print("50th percentile of array : ",np.percentile(farr, 50))
print("25th percentile of array : ",np.percentile(farr, 25))
print("75th percentile of array : ",np.percentile(farr, 75))

print("\nEach Column:")
print("50th Percentile of arr, axis = 0 : ", np.percentile(array, 50, axis=0))
print("25th Percentile of arr, axis = 0 : ", np.percentile(array,25, axis=0))
print("75th Percentile of arr, axis = 0 : ", np.percentile(array,75, axis=0))

print("\nEach Column:")
print("\n50th Percentile of arr, axis = 1 : ",np.percentile(array, 50, axis=1))
print("25th Percentile of arr, axis = 1 : ",np.percentile(array, 25, axis=1))
print("75th Percentile of arr, axis = 1 : ",np.percentile(array, 75, axis=1))

print("\nFlattened array:")
print("Mean: ", np.mean(farr))
print("Median: ", np.median(farr))
print("std: ", np.std(array))

print("\nEach Column:")
print("Mean: ", np.mean(array,axis=0))
print("Median: ", np.median(array,axis=0))
print("std: ", np.std(array,axis=0))

print("\nEach Row:")
print("Mean: ", np.mean(array,axis=1))
print("Median: ", np.median(array,axis=1))
print("std: ", np.std(array,axis=1))

Absolute values: [[1 2 3]
 [4 5 6]]

Flattened Array:
50th percentile of array :  -0.5
25th percentile of array :  -3.5
75th percentile of array :  2.5

Each Column:
50th Percentile of arr, axis = 0 :  [-1.5  1.5 -1.5]
25th Percentile of arr, axis = 0 :  [-2.75 -0.25 -3.75]
75th Percentile of arr, axis = 0 :  [-0.25  3.25  0.75]

Each Column:

50th Percentile of arr, axis = 1 :  [ 1. -4.]
25th Percentile of arr, axis = 1 :  [-0.5 -5. ]
75th Percentile of arr, axis = 1 :  [2.  0.5]

Flattened array:
Mean:  -0.5
Median:  -0.5
std:  3.8622100754188224

Each Column:
Mean:  [-1.5  1.5 -1.5]
Median:  [-1.5  1.5 -1.5]
std:  [2.5 3.5 4.5]

Each Row:
Mean:  [ 0.66666667 -1.66666667]
Median:  [ 1. -4.]
std:  [2.05480467 4.78423336]


In [ ]:
a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0])
print("\nFloor:", np.floor(a))
print("Ceiling: ",np.ceil(a))
print("Truncate Value: ",np.trunc(a))
print("Rounded Value: ",np.round(a))


Floor: [-2. -2. -1.  0.  1.  1.  3.]
Ceiling:  [-1. -1. -0.  1.  2.  2.  3.]
Truncate Value:  [-1. -1. -0.  0.  1.  1.  3.]
Rounded Value:  [-2. -2. -0.  0.  2.  2.  3.]


In [ ]:
array = np.array([10, 52, 62, 16, 16, 54, 453])
print("Array: ", array)
sort_array=np.sort(array)
print("Sorted Array:", sort_array )
print("Indices of Sorted Array: ", sort_array)
print("4 smallest elements are: ", sort_array[:4] )
print("5 largest elements are: ", sort_array[-5:] )


Array:  [ 10  52  62  16  16  54 453]
Sorted Array: [ 10  16  16  52  54  62 453]
Indices of Sorted Array:  [ 10  16  16  52  54  62 453]
4 smallest elements are:  [10 16 16 52]
5 largest elements are:  [ 16  52  54  62 453]


In [ ]:
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])

integer_elements = array[array == np.floor(array)]
print("Integer elements only:", integer_elements)

float_elements = array[array != np.floor(array)]
print("Float elements only:", float_elements)

Integer elements only: [1. 2. 3. 2.]
Float elements only: [1.2 2.2]


In [2]:
from PIL import Image

In [4]:
def img_to_array(path):
    # Open the image file
    img = Image.open(path)

    # Convert image to numpy array
    img_array = np.array(img)

    print(img_array)

    # Determine if the image is RGB or grayscale
    if len(img_array.shape) == 3:  # RGB image
        print("Image is RGB")
    elif len(img_array.shape) == 2:  # Grayscale image
        print("Image is Grayscale")
    else:
        raise ValueError("Unsupported image format")

    # Save the array to a text file
    with open('image_array.txt', 'w') as file:
        np.savetxt(file, img_array.flatten(), fmt='%d')

    print("Image data has been saved to 'image_array.txt'")

img_to_array('download.jpg')

[[[249 233 182]
  [255 240 189]
  [255 245 195]
  ...
  [248 240 203]
  [255 248 206]
  [248 241 195]]

 [[232 216 167]
  [236 220 169]
  [241 223 175]
  ...
  [219 211 172]
  [255 255 214]
  [243 235 188]]

 [[206 189 143]
  [205 189 140]
  [206 189 143]
  ...
  [193 184 141]
  [249 238 192]
  [255 246 195]]

 ...

 [[ 16   9   3]
  [ 16   9   3]
  [ 16   9   3]
  ...
  [ 74  86  14]
  [ 77  84  14]
  [ 77  83  11]]

 [[ 16   9   3]
  [ 16   9   3]
  [ 16   9   3]
  ...
  [ 76  88  16]
  [ 80  87  17]
  [ 80  86  14]]

 [[ 15   8   2]
  [ 15   8   2]
  [ 16   9   3]
  ...
  [ 80  92  20]
  [ 85  92  22]
  [ 85  91  19]]]
Image is RGB
Image data has been saved to 'image_array.txt'
